name: SmartPaste
title: SmartPaste - Intelligent Clipboard Assistant
description: Transform your clipboard into an AI-powered productivity tool across all platforms
baseurl: "/SmartPaste"
url: "https://abdhajjar.github.io"

# GitHub Pages settings
github:
  repository_name: SmartPaste
  repository_url: https://github.com/AbdHajjar/SmartPaste
  owner_name: AbdHajjar
  owner_url: https://github.com/AbdHajjar

# Site metadata
author:
  name: SmartPaste Team
  email: contact@smartpaste.ai

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Include/Exclude
include:
  - _pages
exclude:
  - node_modules/
  - .github/
  - python-lib/
  - tests/
  - "*.log"
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Collections
collections:
  downloads:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_downloads"
    values:
      layout: download

# Custom variables
smartpaste:
  version: "1.0.0"
  release_date: "2025-09-17"
  platforms:
    - name: Windows
      icon: fab fa-windows
      download_url: https://github.com/AbdHajjar/SmartPaste/releases/latest
      description: "Windows 10/11 (x64) - Installer & Portable"
    - name: macOS
      icon: fab fa-apple
      download_url: https://github.com/AbdHajjar/SmartPaste/releases/latest
      description: "macOS 10.15+ (Universal) - DMG & App Bundle"
    - name: Linux
      icon: fab fa-linux
      download_url: https://github.com/AbdHajjar/SmartPaste/releases/latest
      description: "Ubuntu/Debian/Fedora (x64) - AppImage, DEB, RPM"
    - name: Android
      icon: fab fa-android
      download_url: https://github.com/AbdHajjar/SmartPaste/releases/latest
      description: "Android 8.0+ - APK package"
    - name: iOS
      icon: fab fa-apple
      download_url: https://github.com/AbdHajjar/SmartPaste/releases/latest
      description: "iOS 12.0+ - IPA package (TestFlight/Enterprise)"
    - name: Python
      icon: fab fa-python
      download_url: https://pypi.org/project/smartpaste-ai/
      description: "Cross-platform Python library"